# RustIRC Code Formatting Configuration
# All options below are STABLE and work with stable Rust toolchain

# Edition settings (stable)
edition = "2021"
style_edition = "2021"

# Basic formatting (stable)
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Line width (stable)
max_width = 100

# Imports (stable)
reorder_imports = true
reorder_modules = true

# Code organization (stable)
use_field_init_shorthand = true
use_try_shorthand = true

# Miscellaneous (stable)
merge_derives = true