name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      rust_version:
        description: 'Rust version to test'
        required: false
        default: 'stable'
        type: choice
        options:
          - stable
          - beta
          - nightly
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      rust_version:
        description: 'Rust version to test'
        required: false
        default: 'stable'
        type: string
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean
      cache_key:
        description: 'Cache key for sharing build artifacts'
        required: false
        type: string
    outputs:
      test_passed:
        description: 'Whether all tests passed'
        value: ${{ jobs.test.outputs.result == 'success' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  SCCACHE_GHA_ENABLED: "true"
  # RUSTC_WRAPPER set per-job after sccache availability check
  # Global setting removed to prevent systematic failures when sccache unavailable

# Concurrency handled by calling workflow (Master Pipeline)
# to prevent deadlocks when used with workflow_call

jobs:
  # Note: Format and Clippy checks are handled by master-pipeline quick-checks
  # These jobs are kept for standalone CI runs (when not called from master-pipeline)
  fmt:
    name: Format Check
    # Skip if called from master-pipeline (cache_key input is set)
    if: ${{ !inputs.cache_key }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        key: fmt-${{ runner.os }}
    - name: Check formatting
      shell: bash
      run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    # Skip if called from master-pipeline (cache_key input is set)
    if: ${{ !inputs.cache_key }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Run clippy
      shell: bash
      run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    if: ${{ !inputs.skip_tests }}
    outputs:
      result: ${{ steps.test_result.outputs.result }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        exclude:
          # Reduce matrix size by skipping beta on Windows/macOS for faster CI
          - os: windows-latest
            rust: beta
          - os: macos-latest
            rust: beta
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust_version || matrix.rust }}

    # Setup sccache with robust fallback handling
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
      id: sccache

    - name: Configure sccache with fallback (Unix)
      if: ${{ !contains(matrix.os, 'windows') }}
      id: configure_sccache_unix
      shell: bash
      run: |
        # Check if sccache is available and working
        sccache_available="false"
        rustc_wrapper=""

        if command -v sccache > /dev/null 2>&1; then
          echo "sccache binary found, testing functionality..."
          # Test sccache with a timeout to handle hanging
          if timeout 30s sccache --version > /dev/null 2>&1; then
            echo "sccache is working properly"
            # Try to get sccache stats to verify it's actually functional
            if timeout 10s sccache --show-stats > /dev/null 2>&1; then
              sccache_available="true"
              rustc_wrapper="sccache"
              echo "sccache verified and will be used for compilation"
            else
              echo "sccache stats failed, may have connection issues - using fallback"
            fi
          else
            echo "sccache binary found but not working - using direct compilation"
          fi
        else
          echo "sccache not found - using direct compilation"
        fi

        echo "sccache_available=$sccache_available" >> $GITHUB_OUTPUT
        echo "rustc_wrapper=$rustc_wrapper" >> $GITHUB_OUTPUT

        # Export for immediate use in subsequent steps
        echo "RUSTC_WRAPPER=$rustc_wrapper" >> $GITHUB_ENV

        echo "Final configuration: RUSTC_WRAPPER='$rustc_wrapper', available=$sccache_available"

    - name: Configure sccache with fallback (Windows)
      if: contains(matrix.os, 'windows')
      id: configure_sccache_windows
      shell: pwsh
      run: |
        # Check if sccache is available and working
        $sccache_available = "false"
        $rustc_wrapper = ""

        if (Get-Command sccache -ErrorAction SilentlyContinue) {
          Write-Output "sccache binary found, testing functionality..."
          try {
            # Test sccache version
            $null = sccache --version 2>$null
            Write-Output "sccache is working properly"
            # Try to get sccache stats to verify it's actually functional
            try {
              $null = sccache --show-stats 2>$null
              $sccache_available = "true"
              $rustc_wrapper = "sccache"
              Write-Output "sccache verified and will be used for compilation"
            } catch {
              Write-Output "sccache stats failed, may have connection issues - using fallback"
            }
          } catch {
            Write-Output "sccache binary found but not working - using direct compilation"
          }
        } else {
          Write-Output "sccache not found - using direct compilation"
        }

        echo "sccache_available=$sccache_available" >> $env:GITHUB_OUTPUT
        echo "rustc_wrapper=$rustc_wrapper" >> $env:GITHUB_OUTPUT

        # Export for immediate use in subsequent steps
        echo "RUSTC_WRAPPER=$rustc_wrapper" >> $env:GITHUB_ENV

        Write-Output "Final configuration: RUSTC_WRAPPER='$rustc_wrapper', available=$sccache_available"

    - name: Set sccache outputs for compatibility
      id: configure_sccache
      shell: bash
      run: |
        # Unify outputs from platform-specific steps
        if [[ "${{ matrix.os }}" == *"windows"* ]]; then
          sccache_available="${{ steps.configure_sccache_windows.outputs.sccache_available }}"
          rustc_wrapper="${{ steps.configure_sccache_windows.outputs.rustc_wrapper }}"
        else
          sccache_available="${{ steps.configure_sccache_unix.outputs.sccache_available }}"
          rustc_wrapper="${{ steps.configure_sccache_unix.outputs.rustc_wrapper }}"
        fi
        echo "sccache_available=$sccache_available" >> $GITHUB_OUTPUT
        echo "rustc_wrapper=$rustc_wrapper" >> $GITHUB_OUTPUT

    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.cache_key || format('test-{0}-{1}', matrix.os, matrix.rust) }}
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: Cache cargo tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-nextest
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: cargo-tools-${{ matrix.os }}-nextest
        restore-keys: |
          cargo-tools-${{ matrix.os }}-

    - name: Install cargo-nextest with sccache fallback (Unix)
      if: ${{ !contains(matrix.os, 'windows') }}
      shell: bash
      run: |
        if ! command -v cargo-nextest > /dev/null 2>&1; then
          echo "Installing cargo-nextest..."
          # Try with configured RUSTC_WRAPPER first
          if [ "${{ steps.configure_sccache.outputs.sccache_available }}" = "true" ]; then
            echo "Attempting installation with sccache..."
            export RUSTC_WRAPPER="${{ steps.configure_sccache.outputs.rustc_wrapper }}"
            if ! timeout 300s cargo install cargo-nextest --locked; then
              echo "Installation failed with sccache, retrying without sccache..."
              unset RUSTC_WRAPPER
              export RUSTC_WRAPPER=""
              timeout 300s cargo install cargo-nextest --locked
            fi
          else
            echo "Installing without sccache..."
            export RUSTC_WRAPPER=""
            timeout 300s cargo install cargo-nextest --locked
          fi
        else
          echo "cargo-nextest already installed"
        fi

    - name: Install cargo-nextest with sccache fallback (Windows)
      if: contains(matrix.os, 'windows')
      shell: pwsh
      run: |
        if (!(Get-Command cargo-nextest -ErrorAction SilentlyContinue)) {
          Write-Output "Installing cargo-nextest..."
          # Try with configured RUSTC_WRAPPER first
          if ("${{ steps.configure_sccache.outputs.sccache_available }}" -eq "true") {
            Write-Output "Attempting installation with sccache..."
            $env:RUSTC_WRAPPER = "${{ steps.configure_sccache.outputs.rustc_wrapper }}"
            try {
              cargo install cargo-nextest --locked
            } catch {
              Write-Output "Installation failed with sccache, retrying without sccache..."
              Remove-Item Env:RUSTC_WRAPPER -ErrorAction SilentlyContinue
              $env:RUSTC_WRAPPER = ""
              cargo install cargo-nextest --locked
            }
          } else {
            Write-Output "Installing without sccache..."
            $env:RUSTC_WRAPPER = ""
            cargo install cargo-nextest --locked
          }
        } else {
          Write-Output "cargo-nextest already installed"
        }

    - name: Build (if not cached) with sccache fallback
      # Cross-platform build detection
      if: inputs.cache_key == ''
      shell: bash
      run: |
        # Unified bash script for all platforms
        if [ "${{ steps.configure_sccache.outputs.sccache_available }}" = "true" ]; then
          echo "Building with sccache..."
          export RUSTC_WRAPPER="${{ steps.configure_sccache.outputs.rustc_wrapper }}"
          if ! timeout 900s cargo build --all-features --all-targets --release; then
            echo "Build failed with sccache, retrying without sccache..."
            unset RUSTC_WRAPPER
            export RUSTC_WRAPPER=""
            timeout 900s cargo build --all-features --all-targets --release
          fi
        else
          echo "Building without sccache..."
          export RUSTC_WRAPPER=""
          timeout 900s cargo build --all-features --all-targets --release
        fi

    - name: Download build artifacts (if available)
      if: inputs.cache_key != ''
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts-${{ matrix.os }}
        path: target/
      continue-on-error: true
    # Test each package individually with cross-platform commands
    - name: Test rustirc-core
      shell: bash
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Testing package: rustirc-core"
        if ! timeout 600s cargo nextest run -p rustirc-core --release --all-features --profile ci; then
          echo "nextest failed for rustirc-core, trying cargo test..."
          timeout 600s cargo test -p rustirc-core --release --all-features
        fi

    - name: Test rustirc-protocol
      shell: bash
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Testing package: rustirc-protocol"
        if ! timeout 600s cargo nextest run -p rustirc-protocol --release --all-features --profile ci; then
          echo "nextest failed for rustirc-protocol, trying cargo test..."
          timeout 600s cargo test -p rustirc-protocol --release --all-features
        fi

    - name: Test rustirc-tui
      shell: bash
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Testing package: rustirc-tui"
        if ! timeout 600s cargo nextest run -p rustirc-tui --release --all-features --profile ci; then
          echo "nextest failed for rustirc-tui, trying cargo test..."
          timeout 600s cargo test -p rustirc-tui --release --all-features
        fi

    - name: Test rustirc-plugins
      shell: bash
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Testing package: rustirc-plugins"
        if ! timeout 600s cargo nextest run -p rustirc-plugins --release --all-features --profile ci; then
          echo "nextest failed for rustirc-plugins, trying cargo test..."
          timeout 600s cargo test -p rustirc-plugins --release --all-features
        fi

    - name: Test rustirc-scripting
      shell: bash
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Testing package: rustirc-scripting"
        if ! timeout 600s cargo nextest run -p rustirc-scripting --release --all-features --profile ci; then
          echo "nextest failed for rustirc-scripting, trying cargo test..."
          timeout 600s cargo test -p rustirc-scripting --release --all-features
        fi

    - name: Test rustirc-gui (lib only)
      shell: bash
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Testing package: rustirc-gui (lib only)"
        if ! timeout 600s cargo nextest run -p rustirc-gui --release --all-features --lib --profile ci; then
          echo "nextest failed for rustirc-gui, trying cargo test..."
          timeout 600s cargo test -p rustirc-gui --release --all-features --lib
        fi
    # Run doctests individually on Linux to avoid duplication across platforms
    - name: Run doctests for rustirc-core
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for rustirc-core..."
        if timeout 300s cargo test --doc -p rustirc-core --all-features > /dev/null 2>&1; then
          echo "Doctests passed for rustirc-core"
        else
          echo "No doctests or doctest failed in rustirc-core"
        fi

    - name: Run doctests for rustirc-protocol
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for rustirc-protocol..."
        if timeout 300s cargo test --doc -p rustirc-protocol --all-features > /dev/null 2>&1; then
          echo "Doctests passed for rustirc-protocol"
        else
          echo "No doctests or doctest failed in rustirc-protocol"
        fi

    - name: Run doctests for rustirc-gui
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for rustirc-gui..."
        if timeout 300s cargo test --doc -p rustirc-gui --all-features > /dev/null 2>&1; then
          echo "Doctests passed for rustirc-gui"
        else
          echo "No doctests or doctest failed in rustirc-gui"
        fi

    - name: Run doctests for rustirc-tui
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for rustirc-tui..."
        if timeout 300s cargo test --doc -p rustirc-tui --all-features > /dev/null 2>&1; then
          echo "Doctests passed for rustirc-tui"
        else
          echo "No doctests or doctest failed in rustirc-tui"
        fi

    - name: Run doctests for rustirc-scripting
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for rustirc-scripting..."
        if timeout 300s cargo test --doc -p rustirc-scripting --all-features > /dev/null 2>&1; then
          echo "Doctests passed for rustirc-scripting"
        else
          echo "No doctests or doctest failed in rustirc-scripting"
        fi

    - name: Run doctests for rustirc-plugins
      if: contains(matrix.os, 'ubuntu')
      shell: bash
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for rustirc-plugins..."
        if timeout 300s cargo test --doc -p rustirc-plugins --all-features > /dev/null 2>&1; then
          echo "Doctests passed for rustirc-plugins"
        else
          echo "No doctests or doctest failed in rustirc-plugins"
        fi

    # Upload test results to Codecov for Test Analytics
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: target/nextest/ci/junit.xml
        flags: unittests
        name: test-results-${{ matrix.os }}-${{ matrix.rust }}

    - name: Set test result
      id: test_result
      if: always()
      shell: bash
      run: echo "result=success" >> $GITHUB_OUTPUT

  # Note: Coverage and Security Audit are handled by master-pipeline.yml
  # This workflow focuses only on testing across different platforms
  # to avoid redundant execution when called from master-pipeline

  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.75.0
    - uses: Swatinem/rust-cache@v2
    - name: Check MSRV with sccache fallback
      shell: bash
      run: |
        # Unified bash script for all platforms
        sccache_available="false"
        rustc_wrapper=""

        if command -v sccache > /dev/null 2>&1 && timeout 30s sccache --version > /dev/null 2>&1; then
          if timeout 10s sccache --show-stats > /dev/null 2>&1; then
            sccache_available="true"
            rustc_wrapper="sccache"
            echo "Using sccache for MSRV check"
          fi
        fi

        if [ "$sccache_available" = "true" ]; then
          export RUSTC_WRAPPER="$rustc_wrapper"
          if ! timeout 600s cargo check --all-features; then
            echo "MSRV check failed with sccache, retrying without sccache..."
            unset RUSTC_WRAPPER
            export RUSTC_WRAPPER=""
            timeout 600s cargo check --all-features
          fi
        else
          echo "Running MSRV check without sccache"
          export RUSTC_WRAPPER=""
          timeout 600s cargo check --all-features
        fi