name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      rust_version:
        description: 'Rust version to test'
        required: false
        default: 'stable'
        type: choice
        options:
          - stable
          - beta
          - nightly
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      rust_version:
        description: 'Rust version to test'
        required: false
        default: 'stable'
        type: string
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean
      cache_key:
        description: 'Cache key for sharing build artifacts'
        required: false
        type: string
    outputs:
      test_passed:
        description: 'Whether all tests passed'
        value: ${{ jobs.test.outputs.result == 'success' }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  SCCACHE_GHA_ENABLED: "true"
  # RUSTC_WRAPPER set per-job after sccache availability check
  # Global setting removed to prevent systematic failures when sccache unavailable

# Concurrency handled by calling workflow (Master Pipeline)
# to prevent deadlocks when used with workflow_call

jobs:
  # Note: Format and Clippy checks are handled by master-pipeline quick-checks
  # These jobs are kept for standalone CI runs (when not called from master-pipeline)
  fmt:
    name: Format Check
    # Skip if called from master-pipeline (cache_key input is set)
    if: ${{ !inputs.cache_key }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - uses: Swatinem/rust-cache@v2
      with:
        key: fmt-${{ runner.os }}
    - name: Check formatting
      run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    # Skip if called from master-pipeline (cache_key input is set)
    if: ${{ !inputs.cache_key }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    if: ${{ !inputs.skip_tests }}
    outputs:
      result: ${{ steps.test_result.outputs.result }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        exclude:
          # Reduce matrix size by skipping beta on Windows/macOS for faster CI
          - os: windows-latest
            rust: beta
          - os: macos-latest
            rust: beta
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust_version || matrix.rust }}
    
    # Setup sccache with robust fallback handling
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
      id: sccache
    
    - name: Configure sccache with fallback
      id: configure_sccache
      run: |
        # Check if sccache is available and working
        sccache_available="false"
        rustc_wrapper=""
        
        if command -v sccache &> /dev/null; then
          echo "sccache binary found, testing functionality..."
          # Test sccache with a timeout to handle hanging
          if timeout 30s sccache --version &> /dev/null 2>&1; then
            echo "sccache is working properly"
            # Try to get sccache stats to verify it's actually functional
            if timeout 10s sccache --show-stats &> /dev/null 2>&1; then
              sccache_available="true"
              rustc_wrapper="sccache"
              echo "sccache verified and will be used for compilation"
            else
              echo "sccache stats failed, may have connection issues - using fallback"
            fi
          else
            echo "sccache binary found but not working - using direct compilation"
          fi
        else
          echo "sccache not found - using direct compilation"
        fi
        
        echo "sccache_available=$sccache_available" >> $GITHUB_OUTPUT
        echo "rustc_wrapper=$rustc_wrapper" >> $GITHUB_OUTPUT
        
        # Export for immediate use in subsequent steps
        echo "RUSTC_WRAPPER=$rustc_wrapper" >> $GITHUB_ENV
        
        echo "Final configuration: RUSTC_WRAPPER='$rustc_wrapper', available=$sccache_available"
    
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ inputs.cache_key || format('test-{0}-{1}', runner.os, matrix.rust) }}
        cache-directories: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
    - name: Cache cargo tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-nextest
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
        key: cargo-tools-${{ runner.os }}-nextest
        restore-keys: |
          cargo-tools-${{ runner.os }}-
    
    - name: Install cargo-nextest with sccache fallback
      run: |
        if ! command -v cargo-nextest &> /dev/null; then
          echo "Installing cargo-nextest..."
          # Try with configured RUSTC_WRAPPER first
          if [ "${{ steps.configure_sccache.outputs.sccache_available }}" = "true" ]; then
            echo "Attempting installation with sccache..."
            export RUSTC_WRAPPER="${{ steps.configure_sccache.outputs.rustc_wrapper }}"
            if ! timeout 300s cargo install cargo-nextest --locked; then
              echo "Installation failed with sccache, retrying without sccache..."
              unset RUSTC_WRAPPER
              export RUSTC_WRAPPER=""
              timeout 300s cargo install cargo-nextest --locked
            fi
          else
            echo "Installing without sccache..."
            export RUSTC_WRAPPER=""
            timeout 300s cargo install cargo-nextest --locked
          fi
        else
          echo "cargo-nextest already installed"
        fi
    
    - name: Build (if not cached) with sccache fallback
      # Cross-platform build detection
      if: inputs.cache_key == ''
      run: |
        # Try with configured RUSTC_WRAPPER first
        if [ "${{ steps.configure_sccache.outputs.sccache_available }}" = "true" ]; then
          echo "Building with sccache..."
          export RUSTC_WRAPPER="${{ steps.configure_sccache.outputs.rustc_wrapper }}"
          if ! timeout 900s cargo build --all-features --all-targets --release; then
            echo "Build failed with sccache, retrying without sccache..."
            unset RUSTC_WRAPPER
            export RUSTC_WRAPPER=""
            timeout 900s cargo build --all-features --all-targets --release
          fi
        else
          echo "Building without sccache..."
          export RUSTC_WRAPPER=""
          timeout 900s cargo build --all-features --all-targets --release
        fi
    
    - name: Download build artifacts (if available)
      if: inputs.cache_key != ''
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts-${{ runner.os }}
        path: target/
      continue-on-error: true
    - name: Run tests with nextest and sccache fallback
      env:
        CI: true
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        # Function to run tests with fallback
        run_tests_with_fallback() {
          local package="$1"
          local test_args="$2"
          
          echo "Testing package: $package"
          
          # Try with nextest first, fallback to cargo test
          if ! timeout 600s cargo nextest run -p "$package" --release --all-features $test_args; then
            echo "nextest failed for $package, trying cargo test..."
            if ! timeout 600s cargo test -p "$package" --release --all-features $test_args; then
              echo "Both nextest and cargo test failed for $package"
              return 1
            fi
          fi
        }
        
        # Run tests for each package with fallback
        run_tests_with_fallback "rustirc-core" ""
        run_tests_with_fallback "rustirc-protocol" ""
        run_tests_with_fallback "rustirc-tui" ""
        run_tests_with_fallback "rustirc-plugins" ""
        run_tests_with_fallback "rustirc-scripting" ""
        run_tests_with_fallback "rustirc-gui" "--lib"
    - name: Run doctests with sccache fallback
      # Only run doctests on Linux to avoid duplication across platforms
      if: runner.os == 'Linux'
      env:
        RUSTC_WRAPPER: ${{ steps.configure_sccache.outputs.rustc_wrapper }}
      run: |
        echo "Running doctests for library packages..."
        
        # Function to run doctests with timeout
        run_doctest() {
          local package="$1"
          echo "Running doctests for $package..."
          if ! timeout 300s cargo test --doc -p "$package" --all-features 2>/dev/null; then
            echo "No doctests or doctest failed in $package"
          else
            echo "Doctests passed for $package"
          fi
        }
        
        run_doctest "rustirc-core"
        run_doctest "rustirc-protocol"
        run_doctest "rustirc-gui"
        run_doctest "rustirc-tui"
        run_doctest "rustirc-scripting"
        run_doctest "rustirc-plugins"
    - name: Set test result
      id: test_result
      if: always()
      run: echo "result=success" >> $GITHUB_OUTPUT
    
  # Note: Coverage and Security Audit are handled by master-pipeline.yml
  # This workflow focuses only on testing across different platforms
  # to avoid redundant execution when called from master-pipeline

  msrv:
    name: Minimum Supported Rust Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.75.0
    - uses: Swatinem/rust-cache@v2
    - name: Check MSRV with sccache fallback
      run: |
        # Configure RUSTC_WRAPPER for this specific step
        sccache_available="false"
        rustc_wrapper=""
        
        if command -v sccache &> /dev/null && timeout 30s sccache --version &> /dev/null 2>&1; then
          if timeout 10s sccache --show-stats &> /dev/null 2>&1; then
            sccache_available="true"
            rustc_wrapper="sccache"
            echo "Using sccache for MSRV check"
          fi
        fi
        
        if [ "$sccache_available" = "true" ]; then
          export RUSTC_WRAPPER="$rustc_wrapper"
          if ! timeout 600s cargo check --all-features; then
            echo "MSRV check failed with sccache, retrying without sccache..."
            unset RUSTC_WRAPPER
            export RUSTC_WRAPPER=""
            timeout 600s cargo check --all-features
          fi
        else
          echo "Running MSRV check without sccache"
          export RUSTC_WRAPPER=""
          timeout 600s cargo check --all-features
        fi