name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      ignore_advisories:
        description: 'Comma-separated list of advisory IDs to ignore'
        required: false
        default: ''
        type: string
      create_issues:
        description: 'Create GitHub issues for new vulnerabilities'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  issues: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-audit (pinned)
        run: cargo install cargo-audit@0.20.2 --locked

      - name: Run cargo audit
        id: run-audit
        continue-on-error: true
        run: |
          set -e
          cargo audit --json > audit.json

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-json
          path: audit.json
          retention-days: 7

      - name: Create GitHub issue for new vulns
        if: ${{ inputs.create_issues == true }}
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Security audit report - ${{ github.run_id }}"
          content-filepath: audit.json
          labels: security,audit
