name: Security Audit

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      ignore_advisories:
        description: 'Comma-separated list of advisory IDs to ignore (e.g., RUSTSEC-2024-0384,RUSTSEC-2024-0436)'
        required: false
        default: 'RUSTSEC-2024-0384,RUSTSEC-2024-0436'
        type: string
      create_issues:
        description: 'Create GitHub issues for new vulnerabilities'
        required: false
        default: true
        type: boolean
  workflow_call:
    inputs:
      ignore_advisories:
        description: 'Comma-separated list of advisory IDs to ignore'
        required: false
        default: 'RUSTSEC-2024-0384,RUSTSEC-2024-0436'
        type: string
      create_issues:
        description: 'Create GitHub issues for new vulnerabilities'
        required: false
        default: false
        type: boolean
    outputs:
      vulnerabilities_found:
        description: 'Number of vulnerabilities found'
        value: ${{ jobs.security-audit.outputs.vuln_count }}

env:
  CARGO_TERM_COLOR: always

# Concurrency handled by calling workflow (Master Pipeline)
# to prevent deadlocks when used with workflow_call

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    outputs:
      vuln_count: ${{ steps.count_vulns.outputs.count }}
    permissions:
      contents: read
      issues: write
      security-events: write
      actions: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache cargo audit database
      uses: actions/cache@v4
      with:
        path: ~/.cache/cargo-audit
        key: cargo-audit-db-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-audit-db-${{ runner.os }}-

    - name: Run RustSec Security Audit
      uses: rustsec/audit-check@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # Allow unmaintained dependencies that are indirect through GUI frameworks
        # RUSTSEC-2024-0384: instant crate (via iced framework) - unmaintained but actively used
        # RUSTSEC-2024-0436: paste crate (via ratatui/iced frameworks) - unmaintained but actively used
        ignore: ${{ inputs.ignore_advisories || 'RUSTSEC-2024-0384,RUSTSEC-2024-0436' }}

    - name: Install cargo-audit for additional checks
      run: cargo install cargo-audit --locked

    - name: Run comprehensive audit with JSON output
      run: |
        cargo audit --format json --output audit-results.json || true
        echo "Audit completed with exit code: $?"

    - name: Parse audit results and create summary
      run: |
        cat > audit_summary.sh << 'EOF'
        #!/bin/bash
        
        if [ -f "audit-results.json" ]; then
          # Count vulnerabilities by severity
          high_count=$(jq '[.vulnerabilities.list[] | select(.advisory.severity == "high")] | length' audit-results.json 2>/dev/null || echo "0")
          medium_count=$(jq '[.vulnerabilities.list[] | select(.advisory.severity == "medium")] | length' audit-results.json 2>/dev/null || echo "0")
          low_count=$(jq '[.vulnerabilities.list[] | select(.advisory.severity == "low")] | length' audit-results.json 2>/dev/null || echo "0")
          
          echo "# Security Audit Summary" > audit_summary.md
          echo "" >> audit_summary.md
          echo "**Audit Date:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> audit_summary.md
          echo "**Repository:** $GITHUB_REPOSITORY" >> audit_summary.md
          echo "**Commit:** $GITHUB_SHA" >> audit_summary.md
          echo "" >> audit_summary.md
          echo "## Vulnerability Counts" >> audit_summary.md
          echo "- 🔴 High: $high_count" >> audit_summary.md
          echo "- 🟡 Medium: $medium_count" >> audit_summary.md
          echo "- 🟢 Low: $low_count" >> audit_summary.md
          echo "" >> audit_summary.md
          
          total_vulns=$((high_count + medium_count + low_count))
          if [ $total_vulns -gt 0 ]; then
            echo "## Detected Vulnerabilities" >> audit_summary.md
            echo "" >> audit_summary.md
            jq -r '.vulnerabilities.list[] | "### " + .advisory.id + " - " + .advisory.title + "\n" + "**Severity:** " + .advisory.severity + "\n" + "**Package:** " + .package.name + " v" + .package.version + "\n" + "**Description:** " + .advisory.description + "\n"' audit-results.json >> audit_summary.md 2>/dev/null || echo "Error parsing vulnerability details" >> audit_summary.md
          else
            echo "✅ No vulnerabilities detected!" >> audit_summary.md
          fi
        else
          echo "# Security Audit Summary" > audit_summary.md
          echo "" >> audit_summary.md
          echo "❌ Audit results file not found." >> audit_summary.md
        fi
        
        cat audit_summary.md
        EOF
        
        chmod +x audit_summary.sh
        ./audit_summary.sh

    - name: Count vulnerabilities
      id: count_vulns
      run: |
        if [ -f "audit-results.json" ]; then
          total=$(jq '[.vulnerabilities.list[]] | length' audit-results.json 2>/dev/null || echo "0")
        else
          total=0
        fi
        echo "count=$total" >> $GITHUB_OUTPUT

    - name: Upload audit results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-results
        path: |
          audit-results.json
          audit_summary.md
        retention-days: 30

    - name: Comment audit summary on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('audit_summary.md')) {
            const summary = fs.readFileSync('audit_summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🛡️ Security Audit Results\n\n${summary}`
            });
          }

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        config-file: './.github/dependency-review-config.yml'
        comment-summary-in-pr: true
        fail-on-severity: high
        warn-only: false